<?php  return array (
  8 => 
  array (
    'basePath' => '',
    'basePathRelative' => true,
    'baseUrl' => '',
    'baseUrlRelative' => true,
    'allowedFileTypes' => '',
    'imageExtensions' => 'jpg,jpeg,png,gif',
    'thumbnailType' => 'png',
    'thumbnailQuality' => 90,
    'skipFiles' => '.svn,.git,_notes,nbproject,.idea,.DS_Store',
    'id' => NULL,
    'name' => 'Filesystem',
    'description' => '',
    'class_key' => 'modFileMediaSource',
    'properties' => 
    array (
    ),
    'is_stream' => true,
    'source' => 1,
    'object_class' => 'modTemplateVar',
    'object' => 8,
    'context_key' => 'web',
    'source_class_key' => 'sources.modFileMediaSource',
  ),
  9 => 
  array (
    'basePath' => '',
    'basePathRelative' => true,
    'baseUrl' => '',
    'baseUrlRelative' => true,
    'allowedFileTypes' => '',
    'imageExtensions' => 'jpg,jpeg,png,gif',
    'thumbnailType' => 'png',
    'thumbnailQuality' => 90,
    'skipFiles' => '.svn,.git,_notes,nbproject,.idea,.DS_Store',
    'id' => NULL,
    'name' => 'Filesystem',
    'description' => '',
    'class_key' => 'modFileMediaSource',
    'properties' => 
    array (
    ),
    'is_stream' => true,
    'source' => 1,
    'object_class' => 'modTemplateVar',
    'object' => 9,
    'context_key' => 'web',
    'source_class_key' => 'sources.modFileMediaSource',
  ),
  10 => 
  array (
    'basePath' => '',
    'basePathRelative' => true,
    'baseUrl' => '',
    'baseUrlRelative' => true,
    'allowedFileTypes' => '',
    'imageExtensions' => 'jpg,jpeg,png,gif',
    'thumbnailType' => 'png',
    'thumbnailQuality' => 90,
    'skipFiles' => '.svn,.git,_notes,nbproject,.idea,.DS_Store',
    'id' => NULL,
    'name' => 'Filesystem',
    'description' => '',
    'class_key' => 'modFileMediaSource',
    'properties' => 
    array (
    ),
    'is_stream' => true,
    'source' => 1,
    'object_class' => 'modTemplateVar',
    'object' => 10,
    'context_key' => 'web',
    'source_class_key' => 'sources.modFileMediaSource',
  ),
  11 => 
  array (
    'basePath' => '',
    'basePathRelative' => true,
    'baseUrl' => '',
    'baseUrlRelative' => true,
    'allowedFileTypes' => '',
    'imageExtensions' => 'jpg,jpeg,png,gif',
    'thumbnailType' => 'png',
    'thumbnailQuality' => 90,
    'skipFiles' => '.svn,.git,_notes,nbproject,.idea,.DS_Store',
    'id' => NULL,
    'name' => 'Filesystem',
    'description' => '',
    'class_key' => 'modFileMediaSource',
    'properties' => 
    array (
    ),
    'is_stream' => true,
    'source' => 1,
    'object_class' => 'modTemplateVar',
    'object' => 11,
    'context_key' => 'web',
    'source_class_key' => 'sources.modFileMediaSource',
  ),
  12 => 
  array (
    'basePath' => '',
    'basePathRelative' => true,
    'baseUrl' => '',
    'baseUrlRelative' => true,
    'allowedFileTypes' => '',
    'imageExtensions' => 'jpg,jpeg,png,gif',
    'thumbnailType' => 'png',
    'thumbnailQuality' => 90,
    'skipFiles' => '.svn,.git,_notes,nbproject,.idea,.DS_Store',
    'id' => NULL,
    'name' => 'Filesystem',
    'description' => '',
    'class_key' => 'modFileMediaSource',
    'properties' => 
    array (
    ),
    'is_stream' => true,
    'source' => 1,
    'object_class' => 'modTemplateVar',
    'object' => 12,
    'context_key' => 'web',
    'source_class_key' => 'sources.modFileMediaSource',
  ),
  13 => 
  array (
    'basePath' => '',
    'basePathRelative' => true,
    'baseUrl' => '',
    'baseUrlRelative' => true,
    'allowedFileTypes' => '',
    'imageExtensions' => 'jpg,jpeg,png,gif',
    'thumbnailType' => 'png',
    'thumbnailQuality' => 90,
    'skipFiles' => '.svn,.git,_notes,nbproject,.idea,.DS_Store',
    'id' => NULL,
    'name' => 'Filesystem',
    'description' => '',
    'class_key' => 'modFileMediaSource',
    'properties' => 
    array (
    ),
    'is_stream' => true,
    'source' => 1,
    'object_class' => 'modTemplateVar',
    'object' => 13,
    'context_key' => 'web',
    'source_class_key' => 'sources.modFileMediaSource',
  ),
  14 => 
  array (
    'basePath' => '',
    'basePathRelative' => true,
    'baseUrl' => '',
    'baseUrlRelative' => true,
    'allowedFileTypes' => '',
    'imageExtensions' => 'jpg,jpeg,png,gif',
    'thumbnailType' => 'png',
    'thumbnailQuality' => 90,
    'skipFiles' => '.svn,.git,_notes,nbproject,.idea,.DS_Store',
    'id' => NULL,
    'name' => 'Filesystem',
    'description' => '',
    'class_key' => 'modFileMediaSource',
    'properties' => 
    array (
    ),
    'is_stream' => true,
    'source' => 1,
    'object_class' => 'modTemplateVar',
    'object' => 14,
    'context_key' => 'web',
    'source_class_key' => 'sources.modFileMediaSource',
  ),
  15 => 
  array (
    'basePath' => '',
    'basePathRelative' => true,
    'baseUrl' => '',
    'baseUrlRelative' => true,
    'allowedFileTypes' => '',
    'imageExtensions' => 'jpg,jpeg,png,gif',
    'thumbnailType' => 'png',
    'thumbnailQuality' => 90,
    'skipFiles' => '.svn,.git,_notes,nbproject,.idea,.DS_Store',
    'id' => NULL,
    'name' => 'Filesystem',
    'description' => '',
    'class_key' => 'modFileMediaSource',
    'properties' => 
    array (
    ),
    'is_stream' => true,
    'source' => 1,
    'object_class' => 'modTemplateVar',
    'object' => 15,
    'context_key' => 'web',
    'source_class_key' => 'sources.modFileMediaSource',
  ),
  16 => 
  array (
    'basePath' => '',
    'basePathRelative' => true,
    'baseUrl' => '',
    'baseUrlRelative' => true,
    'allowedFileTypes' => '',
    'imageExtensions' => 'jpg,jpeg,png,gif',
    'thumbnailType' => 'png',
    'thumbnailQuality' => 90,
    'skipFiles' => '.svn,.git,_notes,nbproject,.idea,.DS_Store',
    'id' => NULL,
    'name' => 'Filesystem',
    'description' => '',
    'class_key' => 'modFileMediaSource',
    'properties' => 
    array (
    ),
    'is_stream' => true,
    'source' => 1,
    'object_class' => 'modTemplateVar',
    'object' => 16,
    'context_key' => 'web',
    'source_class_key' => 'sources.modFileMediaSource',
  ),
  17 => 
  array (
    'basePath' => '',
    'basePathRelative' => true,
    'baseUrl' => '',
    'baseUrlRelative' => true,
    'allowedFileTypes' => '',
    'imageExtensions' => 'jpg,jpeg,png,gif',
    'thumbnailType' => 'png',
    'thumbnailQuality' => 90,
    'skipFiles' => '.svn,.git,_notes,nbproject,.idea,.DS_Store',
    'id' => NULL,
    'name' => 'Filesystem',
    'description' => '',
    'class_key' => 'modFileMediaSource',
    'properties' => 
    array (
    ),
    'is_stream' => true,
    'source' => 1,
    'object_class' => 'modTemplateVar',
    'object' => 17,
    'context_key' => 'web',
    'source_class_key' => 'sources.modFileMediaSource',
  ),
  18 => 
  array (
    'basePath' => '',
    'basePathRelative' => true,
    'baseUrl' => '',
    'baseUrlRelative' => true,
    'allowedFileTypes' => '',
    'imageExtensions' => 'jpg,jpeg,png,gif',
    'thumbnailType' => 'png',
    'thumbnailQuality' => 90,
    'skipFiles' => '.svn,.git,_notes,nbproject,.idea,.DS_Store',
    'id' => NULL,
    'name' => 'Filesystem',
    'description' => '',
    'class_key' => 'modFileMediaSource',
    'properties' => 
    array (
    ),
    'is_stream' => true,
    'source' => 1,
    'object_class' => 'modTemplateVar',
    'object' => 18,
    'context_key' => 'web',
    'source_class_key' => 'sources.modFileMediaSource',
  ),
  19 => 
  array (
    'basePath' => '',
    'basePathRelative' => true,
    'baseUrl' => '',
    'baseUrlRelative' => true,
    'allowedFileTypes' => '',
    'imageExtensions' => 'jpg,jpeg,png,gif',
    'thumbnailType' => 'png',
    'thumbnailQuality' => 90,
    'skipFiles' => '.svn,.git,_notes,nbproject,.idea,.DS_Store',
    'id' => NULL,
    'name' => 'Filesystem',
    'description' => '',
    'class_key' => 'modFileMediaSource',
    'properties' => 
    array (
    ),
    'is_stream' => true,
    'source' => 1,
    'object_class' => 'modTemplateVar',
    'object' => 19,
    'context_key' => 'web',
    'source_class_key' => 'sources.modFileMediaSource',
  ),
);